title: Nitu's Portfolio
author: GitHub User
email: nitu.sahoo786@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there awesome people! 
  
  I am glad you are here. I would be sharing my coding, photography and cooking exxperience here for which is my life.
  
# social links
github_username:  nitusahoo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
